/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/kai-scheduler/KAI-scheduler/pkg/apis/client/clientset/versioned"
	internalinterfaces "github.com/kai-scheduler/KAI-scheduler/pkg/apis/client/informers/externalversions/internalinterfaces"
	kaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/client/listers/kai/v1alpha1"
	apiskaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GPUGroupTemplateInformer provides access to a shared informer and lister for
// GPUGroupTemplates.
type GPUGroupTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kaiv1alpha1.GPUGroupTemplateLister
}

type gPUGroupTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGPUGroupTemplateInformer constructs a new informer for GPUGroupTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGPUGroupTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGPUGroupTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGPUGroupTemplateInformer constructs a new informer for GPUGroupTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGPUGroupTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaiV1alpha1().GPUGroupTemplates(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaiV1alpha1().GPUGroupTemplates(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaiV1alpha1().GPUGroupTemplates(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaiV1alpha1().GPUGroupTemplates(namespace).Watch(ctx, options)
			},
		},
		&apiskaiv1alpha1.GPUGroupTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *gPUGroupTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGPUGroupTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gPUGroupTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiskaiv1alpha1.GPUGroupTemplate{}, f.defaultInformer)
}

func (f *gPUGroupTemplateInformer) Lister() kaiv1alpha1.GPUGroupTemplateLister {
	return kaiv1alpha1.NewGPUGroupTemplateLister(f.Informer().GetIndexer())
}
