/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "github.com/kai-scheduler/KAI-scheduler/pkg/apis/client/clientset/versioned/scheme"
	kaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GPUGroupsGetter has a method to return a GPUGroupInterface.
// A group's client should implement this interface.
type GPUGroupsGetter interface {
	GPUGroups(namespace string) GPUGroupInterface
}

// GPUGroupInterface has methods to work with GPUGroup resources.
type GPUGroupInterface interface {
	Create(ctx context.Context, gPUGroup *kaiv1alpha1.GPUGroup, opts v1.CreateOptions) (*kaiv1alpha1.GPUGroup, error)
	Update(ctx context.Context, gPUGroup *kaiv1alpha1.GPUGroup, opts v1.UpdateOptions) (*kaiv1alpha1.GPUGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gPUGroup *kaiv1alpha1.GPUGroup, opts v1.UpdateOptions) (*kaiv1alpha1.GPUGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kaiv1alpha1.GPUGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*kaiv1alpha1.GPUGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kaiv1alpha1.GPUGroup, err error)
	GPUGroupExpansion
}

// gPUGroups implements GPUGroupInterface
type gPUGroups struct {
	*gentype.ClientWithList[*kaiv1alpha1.GPUGroup, *kaiv1alpha1.GPUGroupList]
}

// newGPUGroups returns a GPUGroups
func newGPUGroups(c *KaiV1alpha1Client, namespace string) *gPUGroups {
	return &gPUGroups{
		gentype.NewClientWithList[*kaiv1alpha1.GPUGroup, *kaiv1alpha1.GPUGroupList](
			"gpugroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kaiv1alpha1.GPUGroup { return &kaiv1alpha1.GPUGroup{} },
			func() *kaiv1alpha1.GPUGroupList { return &kaiv1alpha1.GPUGroupList{} },
		),
	}
}
