/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "github.com/kai-scheduler/KAI-scheduler/pkg/apis/client/clientset/versioned/scheme"
	kaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GPUGroupTemplatesGetter has a method to return a GPUGroupTemplateInterface.
// A group's client should implement this interface.
type GPUGroupTemplatesGetter interface {
	GPUGroupTemplates(namespace string) GPUGroupTemplateInterface
}

// GPUGroupTemplateInterface has methods to work with GPUGroupTemplate resources.
type GPUGroupTemplateInterface interface {
	Create(ctx context.Context, gPUGroupTemplate *kaiv1alpha1.GPUGroupTemplate, opts v1.CreateOptions) (*kaiv1alpha1.GPUGroupTemplate, error)
	Update(ctx context.Context, gPUGroupTemplate *kaiv1alpha1.GPUGroupTemplate, opts v1.UpdateOptions) (*kaiv1alpha1.GPUGroupTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gPUGroupTemplate *kaiv1alpha1.GPUGroupTemplate, opts v1.UpdateOptions) (*kaiv1alpha1.GPUGroupTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kaiv1alpha1.GPUGroupTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*kaiv1alpha1.GPUGroupTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kaiv1alpha1.GPUGroupTemplate, err error)
	GPUGroupTemplateExpansion
}

// gPUGroupTemplates implements GPUGroupTemplateInterface
type gPUGroupTemplates struct {
	*gentype.ClientWithList[*kaiv1alpha1.GPUGroupTemplate, *kaiv1alpha1.GPUGroupTemplateList]
}

// newGPUGroupTemplates returns a GPUGroupTemplates
func newGPUGroupTemplates(c *KaiV1alpha1Client, namespace string) *gPUGroupTemplates {
	return &gPUGroupTemplates{
		gentype.NewClientWithList[*kaiv1alpha1.GPUGroupTemplate, *kaiv1alpha1.GPUGroupTemplateList](
			"gpugrouptemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kaiv1alpha1.GPUGroupTemplate { return &kaiv1alpha1.GPUGroupTemplate{} },
			func() *kaiv1alpha1.GPUGroupTemplateList { return &kaiv1alpha1.GPUGroupTemplateList{} },
		),
	}
}
