/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GPUGroupListerExpansion allows custom methods to be added to
// GPUGroupLister.
type GPUGroupListerExpansion interface{}

// GPUGroupNamespaceListerExpansion allows custom methods to be added to
// GPUGroupNamespaceLister.
type GPUGroupNamespaceListerExpansion interface{}

// GPUGroupTemplateListerExpansion allows custom methods to be added to
// GPUGroupTemplateLister.
type GPUGroupTemplateListerExpansion interface{}

// GPUGroupTemplateNamespaceListerExpansion allows custom methods to be added to
// GPUGroupTemplateNamespaceLister.
type GPUGroupTemplateNamespaceListerExpansion interface{}

// TopologyListerExpansion allows custom methods to be added to
// TopologyLister.
type TopologyListerExpansion interface{}
