/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GPUGroupTemplateLister helps list GPUGroupTemplates.
// All objects returned here must be treated as read-only.
type GPUGroupTemplateLister interface {
	// List lists all GPUGroupTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kaiv1alpha1.GPUGroupTemplate, err error)
	// GPUGroupTemplates returns an object that can list and get GPUGroupTemplates.
	GPUGroupTemplates(namespace string) GPUGroupTemplateNamespaceLister
	GPUGroupTemplateListerExpansion
}

// gPUGroupTemplateLister implements the GPUGroupTemplateLister interface.
type gPUGroupTemplateLister struct {
	listers.ResourceIndexer[*kaiv1alpha1.GPUGroupTemplate]
}

// NewGPUGroupTemplateLister returns a new GPUGroupTemplateLister.
func NewGPUGroupTemplateLister(indexer cache.Indexer) GPUGroupTemplateLister {
	return &gPUGroupTemplateLister{listers.New[*kaiv1alpha1.GPUGroupTemplate](indexer, kaiv1alpha1.Resource("gpugrouptemplate"))}
}

// GPUGroupTemplates returns an object that can list and get GPUGroupTemplates.
func (s *gPUGroupTemplateLister) GPUGroupTemplates(namespace string) GPUGroupTemplateNamespaceLister {
	return gPUGroupTemplateNamespaceLister{listers.NewNamespaced[*kaiv1alpha1.GPUGroupTemplate](s.ResourceIndexer, namespace)}
}

// GPUGroupTemplateNamespaceLister helps list and get GPUGroupTemplates.
// All objects returned here must be treated as read-only.
type GPUGroupTemplateNamespaceLister interface {
	// List lists all GPUGroupTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kaiv1alpha1.GPUGroupTemplate, err error)
	// Get retrieves the GPUGroupTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kaiv1alpha1.GPUGroupTemplate, error)
	GPUGroupTemplateNamespaceListerExpansion
}

// gPUGroupTemplateNamespaceLister implements the GPUGroupTemplateNamespaceLister
// interface.
type gPUGroupTemplateNamespaceLister struct {
	listers.ResourceIndexer[*kaiv1alpha1.GPUGroupTemplate]
}
