/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kaiv1alpha1 "github.com/kai-scheduler/KAI-scheduler/pkg/apis/kai/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GPUGroupLister helps list GPUGroups.
// All objects returned here must be treated as read-only.
type GPUGroupLister interface {
	// List lists all GPUGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kaiv1alpha1.GPUGroup, err error)
	// GPUGroups returns an object that can list and get GPUGroups.
	GPUGroups(namespace string) GPUGroupNamespaceLister
	GPUGroupListerExpansion
}

// gPUGroupLister implements the GPUGroupLister interface.
type gPUGroupLister struct {
	listers.ResourceIndexer[*kaiv1alpha1.GPUGroup]
}

// NewGPUGroupLister returns a new GPUGroupLister.
func NewGPUGroupLister(indexer cache.Indexer) GPUGroupLister {
	return &gPUGroupLister{listers.New[*kaiv1alpha1.GPUGroup](indexer, kaiv1alpha1.Resource("gpugroup"))}
}

// GPUGroups returns an object that can list and get GPUGroups.
func (s *gPUGroupLister) GPUGroups(namespace string) GPUGroupNamespaceLister {
	return gPUGroupNamespaceLister{listers.NewNamespaced[*kaiv1alpha1.GPUGroup](s.ResourceIndexer, namespace)}
}

// GPUGroupNamespaceLister helps list and get GPUGroups.
// All objects returned here must be treated as read-only.
type GPUGroupNamespaceLister interface {
	// List lists all GPUGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kaiv1alpha1.GPUGroup, err error)
	// Get retrieves the GPUGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kaiv1alpha1.GPUGroup, error)
	GPUGroupNamespaceListerExpansion
}

// gPUGroupNamespaceLister implements the GPUGroupNamespaceLister
// interface.
type gPUGroupNamespaceLister struct {
	listers.ResourceIndexer[*kaiv1alpha1.GPUGroup]
}
